---
title: "wk4-Hw"
output: html_document
date: "2023-10-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Hi There!!
#load the Packages
```{r}
library(janitor)
library(sf)
library(ggplot2)
library(here)
library(tidyverse)
library(tmaptools)
library(tmap)
library(RSQLite)
``` 
# Read the File
#Shape file
```{r}
world_cities <- sf::st_read(here("wk4data", "World_Countries_Generalized", "World_Countries_Generalized.shp"))
```

#.csv file
```{r}
inequality <- read_csv("wk4data/HDR21-22_Composite_indices_complete_time_series.csv", locale = locale(encoding = "latin1"), na = "")
```
#Select the Columns and Calculate the difference
```{r}
inequality_clean <- inequality %>%
  clean_names()%>%
  select(iso3,country,hdicode,hdi_2010,hdi_2011,hdi_2012,hdi_2013,hdi_2014,hdi_2015,hdi_2016,hdi_2017,hdi_2018,hdi_2019) %>%
mutate(difference=hdi_2019-hdi_2010)
```
```{r}
gii_difference <- inequality_clean %>%
  select(iso3,country,hdicode,difference)
```
#Remove the NA values 
```{r}
clean_gii_difference <- na.omit(gii_difference)
```
#Joining Spatial Data with Inequality Index
```{r}
joined_data <- world_cities %>% 
  clean_names() %>%
  left_join(., 
            clean_gii_difference,
            by = c("country" = "country"))
```

```{r}
worlddata <- clean_names(world_cities)
```

```{r}
joined_data1 <- clean_names(joined_data)
```

#Plotting the Data
```{r}

tmap_mode("plot")
qtm(joined_data1, 
    fill = "difference")
```

